image: alpine/edge
secrets:
  - 471107e3-446e-4103-a532-bc9aedeacefb
environment:
  REPO: nvim-config
  MIRROR: vim-config
  GH_USER: theJian
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${MIRROR}"
